float:
  any:
  - base_args: ['@metric']
    constructor: ExpAnnWrapper
    disabled: false
    docker_tag: ann-benchmarks-expann
    module: ann_benchmarks.algorithms.expann
    name: expann
    run_groups:
      rg10:
        arg_groups: [{M: 40, ef_construction: 500, ortho_count: 1, prune_overflow: 0, use_compression: True}]
        args: {}
        query_args: [[10, 20, 30, 40, 50, 80, 120]]
      rg11:
        arg_groups: [{M: 40, ef_construction: 500, ortho_count: 1, prune_overflow: 1, use_compression: True}]
        args: {}
        query_args: [[10, 20, 30, 40, 50, 80, 120]]
      rg13:
        arg_groups: [{M: 40, ef_construction: 500, ortho_count: 1, prune_overflow: 3, use_compression: True}]
        args: {}
        query_args: [[10, 20, 30, 40, 50, 80, 120]]
      rg00:
        arg_groups: [{M: 40, ef_construction: 500, ortho_count: 1, prune_overflow: 0, use_compression: False}]
        args: {}
        query_args: [[10, 20, 30, 40, 50, 80, 120]]
      rg01:
        arg_groups: [{M: 40, ef_construction: 500, ortho_count: 1, prune_overflow: 1, use_compression: False}]
        args: {}
        query_args: [[10, 20, 30, 40, 50, 80, 120]]
      rg03:
        arg_groups: [{M: 40, ef_construction: 500, ortho_count: 1, prune_overflow: 3, use_compression: False}]
        args: {}
        query_args: [[10, 20, 30, 40, 50, 80, 120]]
