float:
  any:
    base_args: ['@metric']
    constructor: ExpAnnWrapper
    disabled: false
    docker_tag: ann-benchmarks-expANN
    module: ann_benchmarks.algorithms.expANN
    name: expANN
    run_groups:
      base:
        args: |
          [{"M":70}]
        query_args: |
          [{"Ls":50}]
